### ISSUE TITLE
Is it possible to forward all ports or just bind ip?

### ISSUE THREAD

**Issue by remoteweb** [tianon/docker-qemu#15]
Hi guys,

wondering if it's possible to bind the whole address to the VM or forward all or range of ports.

Already managed to overcome docker container whole ip assignment with vlan but cannot do the same with the VM running inside.

**Comment by tianon** [comment]
Honestly, I think you probably want to stop using the userspace networking option at this point and switch over to a proper TAP connection (which is going to be more complicated to set up, but is going to give you a much better experience in the long run): https://wiki.qemu.org/Documentation/Networking#Tap

**Comment by remoteweb** [comment]
Thanks you @tianon . Will check that.

**Comment by shami3** [comment]
Hi guys,
to achieve TAP networking in a limited environment like Docker in Synology, could you add an environment variable to append arguments to the QEMU command line? something like QEMU_ARGS_EXTRA.

Thank you :)
