### ISSUE TITLE
Is VNC supported ??

### ISSUE THREAD

**Issue by Zeldri** [tianon/docker-qemu#3]
Hi I just wanted to ask if VNC is actually supported, because I didn't see any VNC mention in the files :/ That's may be a dumb question ^^ Thx for the work :D

**Comment by Zeldri** [comment]
Nervermind, of course it's supported... Just need to add `-p 5900:5900` I'm an idiot 😂😂

**Comment by tianon** [comment]
It is enabled by default, but it is passwordless, so I'd recommend some caution around exposing it external to your machine (which is what that will do).

I typically connect to the container IP directly instead.

**Comment by Zeldri** [comment]
> It is enabled by default, but it is passwordless, so I'd recommend some caution around exposing it external to your machine (which is what that will do).
> 
> I typically connect to the container IP directly instead.

By directly, you mean to open the port only for the container's ip ? Because without opening it, this will not going to work, right ?

**Comment by tianon** [comment]
I mean, if I do `docker run ... --name xyz tianon/qmeu ...`, I then do essentially `docker container inspect xyz` to find the container IP and connect to that directly, and avoid doing `-p` at all.

(In actuality, I do the `inspect` via https://github.com/tianon/rawdns, so I really just do something like `gvncviewer qemu-xyz.docker` and it DTRT :+1:)
