### ISSUE TITLE
Need more accurate test on /dev/kvm

### ISSUE THREAD

**Issue by infinnovation-dev** [tianon/docker-qemu#4]
If running as a non-privileged user, e.g. using singularity or (untested) podman rather than docker, and /dev/kvm has restricted permissions, the test on the existence of /dev/kvm may lead start-qemu to set the -enable-kvm flag which then doesn't work.  Perhaps

    if [ -r /dev/kvm ]; then

would be better?

**Comment by tianon** [comment]
I agree a more robust test would be great -- my only concern is that we need to also ensure the test ensures our cgroup has access, which I think is possibly harder than just `test -r`? (not sure)

**Comment by tianon** [comment]
Just to come back and confirm my suspicions here:

```console
$ docker run --rm -v /dev/kvm:/kvm:ro bash test -w /kvm; echo $?
0
```

(Both `test -r` and `test -w` are insufficient :disappointed:)

**Comment by tianon** [comment]
Here's an idea that might work, but I have no idea how abusive this is to this kernel interface: :weary:

```console
$ docker run --rm -v /dev/kvm:/kvm bash -c 'echo -n > /kvm'; echo $?
bash: line 1: /kvm: Operation not permitted
1
$ docker run --rm --device /dev/kvm:/kvm bash -c 'echo -n > /kvm'; echo $?
0
```

**Comment by tianon** [comment]
Reading through https://lwn.net/Articles/658511/, this seems pretty sane -- thanks for filing the issue, and sorry it took me so long to find a better solution! :sweat_smile:
