### ISSUE TITLE
use alpine as base image?

### ISSUE THREAD

**Issue by psy0rz** [tianon/docker-qemu#40]
Would this be possible, or is there a special reason you compile qemu yourself?

The current stable version of alpine has qemu 7.0.

**Comment by tianon** [comment]
(Also the sheer size of compiled builds of QEMU make me doubt that an Alpine-based image really would be _significantly_ smaller, and size is typically the motivator I see when folks turn to Alpine-based images.)

**Comment by psy0rz** [comment]
well, i tried, the difference in size is astounding:
```
test                        latest    aec5d13d3dc4   5 minutes ago   61.7MB
tianon/qemu                 latest    4adcb3e7e942   2 days ago      1.54GB
```

I only installed qemu-system-x86_64:

```
psy@psyt14s:~/ansible$ docker run -it --rm test-qemu
/ # qemu-system-x86_64 --version
QEMU emulator version 7.0.0
Copyright (c) 2003-2022 Fabrice Bellard and the QEMU Project developers
/ # 
psy@psyt14s:~/ansible$ docker run -it --rm tianon/qemu /bin/bash
root@97e39562ada2:/# qemu-system-x86_64 --version
QEMU emulator version 7.1.0 (https://github.com/tianon/docker-qemu)
Copyright (c) 2003-2022 Fabrice Bellard and the QEMU Project developers
```

**Comment by psy0rz** [comment]
(i offcourse tried and it boots my .iso)

**Comment by psy0rz** [comment]
a very interesting side effect: your compiled version reacts correctly to a SIGHUP.

when i use the qemu binary from alpine or ubuntu, it just terminates immeadiatly on a SIGHUP without shutting down the VM operating system correctly. (via acpi)

**Comment by psy0rz** [comment]
ah https://github.com/tianon/docker-qemu/blob/master/7.1/qemu-signals.patch

**Comment by berlin4apk** [comment]
@psy0rz can you publish your work? so i can use it as the base for a PR to add, a Alpine-based image, it as a slim size alternative docker image version.

@tianon Im also running in problems with the docker image size.
(getting spamed with "No space left on device" on my docker hosts :-) )

**Comment by tianon** [comment]
If you're not already using the "native" variants and are only using KVM
and not emulation, you should definitely consider switching (they're only
~500MiB instead of 1.5GiB, and only support a single architecture instead
of a huge number of architectures).
