### ISSUE TITLE
Add arm64 image

### ISSUE THREAD

**Issue by axelfontaine** [tianon/docker-qemu#47]
Currently only an amd64 is being produced. However an arm64 image would be very useful on Apple Silicon Macs.

**Comment by tianon** [comment]
Unfortunately, the way I currently build these makes this a little hard for me to accomplish, but I do write the `Dockerfile`s such that they _should_ build successfully on arm64 (and I do aspirationally _want_ to build them for both someday :sweat_smile:).

It would be useful to have folks verifying that assumption by attempting to build for arm64, but I can't make any promises on my own timeline for producing builds. :bow:

**Comment by tianon** [comment]
This is now fixed (but only for the `-native` variants, which is all I plan to support here). :+1:

https://explore.ggcr.dev/?image=tianon/qemu:8.1-native
