### ISSUE TITLE
[help] How do i connect into the ssh?

### ISSUE THREAD

**Issue by Vann-Dev** [tianon/docker-qemu#50]
I've forward my ssh port from qemu into port 2223, but I cant connect it using ssh, or I messed up?

```bash
docker run -it --rm \
	--device /dev/kvm \
	--name qemu-tianon \
	-e QEMU_HDA_SIZE=1G \
	-e QEMU_CPU=1 \
	-e QEMU_RAM=512 \
	-v /home/vann/qemu-tianon/alpine-virt-3.19.1-x86_64.iso:/tmp/debian.iso:ro \
     	-e QEMU_CDROM=/tmp/debian.iso \
	-e QEMU_BOOT='order=d' \
	-p 2223:22 \
	--cap-add NET_ADMIN \
	tianon/qemu:native \
	start-qemu -net user,hostfwd=tcp::2223-:22 -net nic
```

![image](https://github.com/user-attachments/assets/423d5a4b-d136-4b1d-b399-37e0bd9cb331)

Also the docker run normally, but only i want to learn how do i connect into the qemu ssh
![image](https://github.com/user-attachments/assets/b6fd7a98-3454-4610-9620-93a469d6c360)

**Comment by Vann-Dev** [comment]
Found another way 😃

**Comment by tianon** [comment]
Nice, glad you got it figured out!  What I normally do is connect to port 22 on the container (using https://github.com/tianon/rawdns so I can do `ssh container-name.docker` directly), so that I don't have to expose the port external to the Docker host.

**Comment by tianon** [comment]
Oh, I think what's going wrong is that you've specified `-net` with my `start-qemu` wrapper script, which you probably don't want unless you _also_ disable this block (so if you want to use the wrapper, it's going to be easier to take advantage of/use this instead):

https://github.com/tianon/docker-qemu/blob/e4a3f54d9b32ad7643efaaf2b8d1d99eeae8d748/start-qemu#L75-L95

**Comment by Vann-Dev** [comment]
Ahhh i see, i will try using your solution sir, thanks for the reply too
